#pragma config(Motor,  motor1,          LeftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          LeftArm,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         RightArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         RightMotor,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//TO ANY FUTURE PROGRAMMERS THE ERROR IS MOTOR 12 IS NOT RECOGNIZED
task main()
{
	while (true) {

		if (getJoystickValue(ChA)) {
			setMotorSpeed(LeftMotor, getJoystickValue(ChA) * 1.28);
			setMotorSpeed(RightMotor, getJoystickValue(ChB) * 1.28);

		}
		else {
			setMotorSpeed(LeftMotor, 0);
			setMotorSpeed(RightMotor, 0);
		}

		if(getJoystickValue(BtnRUp)){
			setMotorSpeed(RightArm, 128);
			setMotorSpeed(LeftArm, 128);
		}
		else {
			setMotorSpeed(RightArm, 0);
			setMotorSpeed(LeftArm, 0);
		}


	}


}
